### ISSUE TITLE
Increase recursion limit by default

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#152]
For my model, I quickly ran into the recursion limit issue (just as with the markov chain model). It might be a good idea to increase the recursion limit by default.

**Comment by rizar** [comment]
Sound like a reasonable thing to do. The worst thing is that `blocks-continue` called without changing the maximum recursion depth can screw your model up. Btw, I think we should pickle to a temporary file and then perform replacement, because pickling errors are so frequent and their consequences are so disastrous.

**Comment by bartvm** [comment]
How can it screw your model up? If the file is opened in read-only mode, I really don't see how it could screw up a correctly pickled model?

**Comment by bartvm** [comment]
Oh wait, I guess that you mean it tries to overwrite the old, correct model and then fails when doing so, got it! Never had that, because I always move my models before resuming training.

**Comment by bartvm** [comment]
Fixed in #259.
