### ISSUE TITLE
Change use of global seed

### ISSUE THREAD

**Issue by bartvm** [bartvm/blocks#180]
@dwf pointed out correctly that in the current implementation, bricks created separately from each other will use the same seed, and so will have exactly the same weights (assuming they use the same initialization scheme).

It could be an idea to create a single global RNG to attach to the `Brick` class. That way we can still set a global seed that this RNG will be initialized with, but it won't be re-used

**Comment by dwf** [comment]
A single global RNG has the advantage that at least programs are deterministic and not reusing seeds in weird ways, but the disadvantage that the numbers generated will depend on the order of object creation. This makes it hard to pull specific objects out and reproduce their behaviour in a different operating environment.

One way to make this work is to implement a policy of objects explicitly storing the seeds they used to initialize some generator/parameters/whatever. Then,

* If a seed is provided at object creation time, store it and use it.
* If a seed is not provided, sample a seed from the global `Brick` random number generator, store it, and use it.

Then at least if you want to reproduce the behaviour of a given `Brick` you will have the seed that was  available to you in your post-mortem, without having to step through the exact program you ran in order to get it.
