### ISSUE TITLE
Serialization problem with Adadelta

### ISSUE THREAD

**Issue by arasmus** [bartvm/blocks#245]
I get
```RuntimeError: maximum recursion depth exceeded```

I have no idea what's going on. I tried to change mnist example to use Adadelta, but serialization starts failing. I tracked the problem a little bit, but couldn't figure it out easily. See this commit for repro instructions:

https://github.com/arasmus/blocks/commit/f7c2bd97a9c870d13389d769b5d563f3743a1914

**Comment by dwf** [comment]
CC @vdumoulin

**Comment by rizar** [comment]
There is even issue about that: #152.

For some reason, dill, the package we use for serialization, uses crazy deep recursion. So try simply increasing the recursion limit until we find a more general solution for that.

**Comment by vdumoulin** [comment]
@rizar If I understand correctly, `AdaDelta` exhibits the problem with recursion limit but is not directly causing it? I'd be curious to know if there's something I did while writing `AdaDelta` which should be done in another way in order to prevent these things from happening.

**Comment by bartvm** [comment]
There's nothing I'm aware of that you could easily change to prevent this from happening. The problem is basically that a large, annotated Theano graph creates a deep object hierarchy with many circular references. When `cPickle` or `dill` tries to serialize this, it quickly runs into recursion errors. (Note that `mlp.py` in Pylearn2 also increases the recursion limit to deal with this.) It's annoying, but it's not actually a problem; the recursion limit in Python is set pretty low, to make sure that infinite recursions don't take too long to break out of. Simply increasing it solves all cases I've seen so far.
