### ISSUE TITLE
Scrutinizer Writes `Errored` but Draws a Nice Green Icon

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#262]
People keep ignoring Scrutinizer error reports because instead of a red cross it draws this nice I-do-not-know-its-name icon.

**Comment by bartvm** [comment]
You mean the green checkmark?

I configured Scrutinizer to only give errors when flake8 or the docstring checker don't pass. All other concerns (PyLint, etc.) don't give errors, mostly because many of these errors are good practice, but are sensible to ignore in certain situations (e.g. constants should be upper case, but we allow `logger`). Almost any PR will cause some of these warnings which are acceptable to ignore (especially because sometimes PyLint gets confused by our lazy initialization).

There are basically two options: Raise an error even in these cases, forcing the committer to have a look, but be okay with merging failed scrutiziner tests; or the current option, where we don't merge if it fails, but encourage people to have a look at the other errors it reports.

**Comment by rizar** [comment]
Yes, checkmark, that's how it is called :)

The problem is we have now checkmarks even in the case when flake8 or docstring check fail (open any recent PR and see).

**Comment by bartvm** [comment]
Any in particular? Can't run flake8 myself to check right now, and
Scrutinizer seems happy with all the recent PRs; flake8 and pep257 had exit
code 0 it says.

**Comment by rizar** [comment]
For instance this one https://github.com/bartvm/blocks/pull/263. Open the Scrutinizer report and scroll down:

```
blocks/bricks/conv.py:10 in public class `Convolutional`:
        D202: No blank lines allowed *after* class docstring, found 1
blocks/bricks/conv.py:224 in public class `Flattener`:
        D504: Docstring exceeds 75 characters
```

**Comment by bartvm** [comment]
Ah, I see, that's very strange... I didn't change any of the configuration as far as I remember, and the build is clearly labelled as failed on Scrutinizer, so there might be something wrong on their side. I'll have a look and contact them otherwise.

**Comment by bartvm** [comment]
This seems to have been resolved, guess it was just some sort of bug on their side.
