### ISSUE TITLE
Support for storing datasets in GPU memory

### ISSUE THREAD

**Issue by arasmus** [bartvm/blocks#265]
It is probably faster to store small datasets like MNIST in GPU memory (as shared) and only pass in the mb index or range to the function. Are there any plans for implementing this?

**Comment by bartvm** [comment]
No plans for it yet. Although it could be faster, I'd argue that we need some real performance benchmarks to see whether it is worth the effort. Mostly because it would require pretty fundamental changes, since it means circumventing large parts of the data stream/dataset pipeline.

**Comment by rizar** [comment]
Well, it is sort-of possible without fundamental changes. One can write a stream wrapper that fetches all the epoch data and loads it into a shared variable. Instead of returning data this wrapper can return indices. The user is the responsible to build his computation graph in such a way that the accumulator variable from the wrapper is a part of it and that its inputs are indices, not data.

Not too difficult, I would say.

**Comment by bartvm** [comment]
Right, I was thinking about how to make it completely transparent, but this solution sounds much better.

**Comment by rizar** [comment]
I close this issue: it can implemented with Blocks but is not urgent in any way.
