### ISSUE TITLE
'Building with bricks'  tutorial typos and improvements

### ISSUE THREAD

**Issue by fvisin** [bartvm/blocks#338]
Hey,

I have a few comments on the _Building with bricks tutorial_:

1. In the _lazy initialization_ section you claim:

    > In the example above we configured the Linear brick during initialization.

    If I am not wrong, this should be 'during configuration'
2. In the sentence:

    > which is quite common: We want to take the output of one model,

    'we' should be lowercase
3. It would be nice to explicit the lifecycle of a brick object earlier in the tutorial, maybe with a very simple graph (`construction/configuration` --> `further configuration` --> `allocation` --> `initialization`). Also, I think that an introductory part briefly explaining the meaning of each life phase would be of help to comprehend the rest.

4. Finally, in the Brick documentation

    > Allocation configuration of children

    is not very clear.

**Comment by bartvm** [comment]
1. There's a confusion here between *parameter initialization* and *object initialization* (which is what the `__init__` method does). "Configuration" is also ambiguous though, because you can configure a brick at any point *after* initialization (but before calling `Brick.apply` or `Brick.initialize`).
2. Depends on which style guide you choose. Chicago agrees with you, AP doesn't for example. I don't think we've gotten to the point yet where we have decided which style guide to stick with...
3. Feel free to make a PR which you think clarifies things. It's probably better to get editing suggestions from someone who's going through the tutorials for the first time, than for me to edit it.
4. Ditto.

**Comment by fvisin** [comment]
Addressed point 3 in https://github.com/bartvm/blocks/pull/473
