### ISSUE TITLE
Rename roles to all be singular

### ISSUE THREAD

**Issue by arasmus** [bartvm/blocks#363]
Currently there are ```WEIGHTS```, ```BIASES```, ```FILTERS``` but on the other hand there are ```PARAMETER```, ```INPUT```, ```OUTPUT```. Is there a reason for mixing singulars and plurals?

Also ```WeightsRole``` inherits ```ParameterRole```, so it applies to class naming too.

**Comment by rizar** [comment]
`WEIGHTS` should be read as "a matrix of weights". Does it make sense now?

**Comment by bartvm** [comment]
Mm, I guess it's all a bit unclear. When I wrote `INPUT` I was thinking of the variable being an `INPUT`, and since the role is attached to a single variable, I made it singular. Regarding weights, it's not referring to the variable being a weight, but being a matrix of weights, hence plural.

It's fairly arbitrary though, because `INPUT` is normally a matrix or vector as well (although it doesn't have to be) and could conceivable be plural in that case (as in, the *inputs* to your hidden layer).

To me the current naming scheme sounds fairly natural, but that could just be me. If you have a better proposal we could consider it, but I think it's not too bad right now.

**Comment by arasmus** [comment]
```WEIGHTS``` could as well be "weight matrix" or "weight tensor" and ```BIASES``` a "bias vector". I could also combine several "weight matrices" into a tensor and call that a "a tensor of parameters". :-)

I prefer consistency: all singular or all plural. And, IMO, singular is more natural here. But it's totally up to you.

**Comment by bartvm** [comment]
I like consistency too, so there's definitely an argument there. Because this seems like something that is very much a personal preference, let's just ping a few people about their preferences!

@dwf @pbrakel @vdumoulin @jbornschein Do you prefer `WEIGHT`/`BIAS` or `WEIGHTS`/`BIASES`, the first one being more consistent with `INPUT`, `OUTPUT` and `PARAMETER` being singular.

**Comment by vdumoulin** [comment]
I'd go with everything singular, for the sake of consistency.

**Comment by pbrakel** [comment]
Is this only about the roles? In most cases, plural sounds more natural to me unless there is truly just one parameter (like the learning rate) but when assigning a role, that role is a singular thing that can be seen as a title that applies to every individual parameter/variable. If the choice is 50/50, singular is shorter -> fewer line breaks.

**Comment by dwf** [comment]
I agree with @pbrakel that WEIGHTS and BIASES seems more natural to me. I'm
unopinionated about PARAMETER vs PARAMETERS.

**Comment by jbornschein** [comment]
I was also confused by this and wanted to file a bug report about the inconsistency. 

I agree with @dwf that the plural form seems more natural: Filtering for BIASES, WEIGHTS or PARAMETERS  sounds just "right". When assigning roles the singular term seems slightly preferable though. Still, I would weight in for plural.

But I would value consistency much higher than singular vs. plural.

**Comment by bartvm** [comment]
Haha, I have to say that I have difficulty understanding which side @pbrakel and @jbornschein are on...

@jbornschein You say that you would weigh in for plural, but that you value consistency more. Does that mean you want to change `INPUT` to `INPUTS`, etc.?

@pbrakel Yes, this is just about assigning a role to a variable, nothing else. Do I understand correctly that you prefer singular in that case?

**Comment by jbornschein** [comment]
Just wrote a correction to my last comment.

To clarify: Yes, initially I thought we can easily change and make all roles plural. But after recognizing there are already many roles and for some of them the plural form does not sound very intuitive.
As such I vote for singular.

**Comment by pbrakel** [comment]
I also vote singular for roles. I just thought it might also be an issue for the naming of some of the method arguments like `input_` vs `inputs` but that would be another issue I guess.

**Comment by bartvm** [comment]
Yeah, good point, but let's keep it to one renaming operation a day :)

I think consistent singular definitely seems to be the preference.

**Comment by vdumoulin** [comment]
Would it be possible to stick with singular but also accept the plural form as argument in setting roles and filtering variables?

**Comment by bartvm** [comment]
Possible, yes, but a bit confusing when we start automatically renaming variables behind the scenes. I'd rather keep it simple.

**Comment by vdumoulin** [comment]
Fair point.

**Comment by dwf** [comment]
Assigned to @mducoffe this week.
