### ISSUE TITLE
Default filtering of graph in TrainingAlgorithm: maybe use roles?

### ISSUE THREAD

**Issue by arasmus** [bartvm/blocks#364]
Currently ```DifferentiableCostMinimizer``` finds parameters for gradient calculation simply by taking all ```shared_variables``` by default . Is this a design decision? To me this sounds like it should filter based on ```PARAMETER``` role. Maybe use ```shared_variables``` only if no item with role ```PARAMETER``` was found in case someone has created their custom graph and didn't bother with roles.

I bumped into this after adding a noise source by manually creating RandomStream. Apparently RandomStream internally uses shared variables and injects some to the graph causing ```theano.tensor.grad``` to fail

```      
 self.params = (params if params
                       else ComputationGraph(cost).shared_variables)
```

**Comment by bartvm** [comment]
Yes, that's a design decision, one that's lead to quite a bit of discussion :)

The main reason is that I'm a very strong proponent of not introducing dependencies all throughout the framework. That means that algorithms shouldn't depend on annotated variable roles just to be useful. Ideally, someone should be able to copy-paste the algorithm and use it on a raw Theano model outside of Blocks if you ask me.

Also, we've always said that you can mix Blocks code and raw Theano code. If you rely on the `PARAMETER` role, then suddenly your raw Theano code won't be trained, which obviously isn't ideal either.

However, this particular case is confused because of something else as well: We would like to exclude random streams from `ComputationGraph.shared_variables`, and we actually do exclude standard random streams. However, `MRG_RandomStreams` are indistinguishable from real shared variables! In order to fix this, we would need to do something more clever in the `ComputationGraph.shared_variables` property. Namely, if a shared variable is the input to an `MRG_RNG` Theano op it should be excluded from the list.

For a quick fix, just pass the parameters to the algorithm manually using something like `params=[param for param in cg.params if param is not rng_variable]`.

**Comment by rizar** [comment]
Sorry for that: we know about this issue but keep arguing what is the right way to handle these things. On the one hand, we do not want the `blocks/algorithm` submodule to depend on Blocks too much and have too many magic defaults in it. On the other hand, making the user always write this:

```
algorithm = GradientDescent(
    cost=cost, VariableFilter(roles=[PARAMETER])(cg.shared_variables), ...)
```

seems an overkill. So my proposal is to (a) clear `blocks/algorithm` from all occurences of `ComputationGraph` (b) add `get_parameters` method to the `ComputationGraph` which would the filtering like in the code above. This way we arrive to 

```
algorithm = GradientDescent(
   cost, ComputationGraph(cost).get_parameters(), ...)
```

which I think is okay. Alternatively it may be `parameters` property. 

@bartvm , are you fine with such a solution?

**Comment by bartvm** [comment]
Yes, that's the kind of solution I would like to see!

We also need to filter out those damned GPU random streams though.

**Comment by arasmus** [comment]
I like @rizar's suggestion :+1:

**Comment by bartvm** [comment]
Oh, and I prefer `parameters` as a property, just because it's consistent with the other properties such as `shared_variables`, etc.

**Comment by rizar** [comment]
> and we actually do exclude standard random streams

I think currently we don't.

> We also need to filter out those damned GPU random streams though.

We can do this to make `shared_variables` list as clean as possible, but as we have already discussed there are cases when a shared variable is not a parameter. So we leave the final choice to the user: he can either use `shared_variables` or `parameters`. For Blocks-only models the second is the natural choice, for Theano-only the first, but let's not try to be  super-intelligent and guess what he wants. We are lean and we are mean!

**Comment by rizar** [comment]
@arasmus , if you wish you can make a PR with this change and we will be happy to merge it!

**Comment by bartvm** [comment]
https://github.com/bartvm/blocks/blob/master/blocks/utils.py#L265

**Comment by rizar** [comment]
@bartvm, sorry, my bad!

By the way, two more things about the `parameters` attribute we want to add:

* it must not use `VariableFilter`, otherwise we have a dependency loop. 

* it is still an on-going debate whether a non-shared variable can have the `PARAMETER` role. So I am inclined to make it return only both shared and `PARAMETER` variables in this call. But the the name `parameters` is not fully appropriate. So maybe `shared_parameters`?

**Comment by bartvm** [comment]
Ah, right, we need to pick up that debate sometime, but I vaguely remember agreeing with you in the end (I think it was agree, I can't remember?) and to not copy roles. Instead just give them a new role e.g. `NOISED` and a tag `replaced` referring to the variable they replaced. `VariableFilter`'s behavior should then just be a bit more intelligent, and be controlled with some keyword arguments.

Anyway, I agree that it should only return shared parameters, assuming that this is what it's primary purpose would be. I prefer just sticking with `parameters` though. The fact that it's only 90% and not 100% appropriate is only relevant to the one or two people who are intimately familiar with the way roles and replacements work. For everyone else, it will just be confusing as to way it uses the more obscure `shared_parameters` instead of `parameters` (which in their eyes, is probably even redundant, even though it's not as simple if you really, really go into the details).

**Comment by rizar** [comment]
On 26.02.2015 18:28, Bart van Merriënboer wrote:
>
> Ah, right, we need to pick up that debate sometime, but I vaguely 
> remember agreeing with you in the end (I think it was agree, I can't 
> remember?) and to not copy roles. Instead just give them a new role 
> e.g. |NOISED| and a tag |replaced| referring to the variable they 
> replaced. |VariableFilter|'s behavior should then just be a bit more 
> intelligent, and be controlled with some keyword arguments.
>
Right, we converged on something like that. But there are other cases 
when a PARAMETER variable can be not shared, e.g. autoencoders with tied 
weights.
>
> Anyway, I agree that it should only return shared parameters, assuming 
> that this is what it's primary purpose would be. I prefer just 
> sticking with |parameters| though. The fact that it's only 90% and not 
> 100% appropriate is only relevant to the one or two people who are 
> intimately familiar with the way roles and replacements work. For 
> everyone else, it will just be confusing as to way it uses the more 
> obscure |shared_parameters| instead of |parameters| (which in their 
> eyes, is probably even redundant, even though it's not as simple if 
> you really, really go into the details).
>
Both fine with me. When we finally think the roles through of if we get 
complains we can rename it again.

By the way, this innocent change breaks all scripts ever written in 
Blocks, so we should make a mail-list announcement as soon as it is done.

**Comment by bartvm** [comment]
> Right, we converged on something like that. But there are other cases
when a PARAMETER variable can be not shared, e.g. autoencoders with tied
weights.

Right, good point.

Let's have an announcement ready when merging.

**Comment by arasmus** [comment]
Yeah, I can do a PR for this.
