### ISSUE TITLE
Model and algorithm relationship

### ISSUE THREAD

**Issue by adbrebs** [bartvm/blocks#386]
A last question that arose from the tutorial. When you create the training algorithm
algorithm = GradientDescent(cost=cost, params=cg.parameters, step_rule=Scale(learning_rate=0.1))
you provide the cost and the parameters, but why those should belong to the algorithm object? The algorithm uses the cost to update the parameters but there is no membership relation. An object algorithm should live without any cost or parameters, no?
As a result you don't provide any model to the MainLoop (the model is hidden in the algorithm) which seems strange. Wouldn't it be better to separate Algorithm and Model? And do the connection in the MainLoop?

**Comment by bartvm** [comment]
I think you can look at it in many ways, but the algorithm in the end is `theta <- theta - dL/dtheta`, so you can easily argue that these variables should be part of the algorithm.

But there is a much more important argument here, modularity: The idea is that a user should basically be able to copy-paste algorithms in and out of Blocks, without the need to use abstractions such as "model". Right now you could write your entire model in raw Theano and simply call `GradientDescent` in the end with your cost and parameters. No need to wrap your Theano code in a new `Model` abstraction that provides `get_cost` and `get_parameters` methods. Vice-versa, if I wrote a cool algorithm and want to put it into blocks, I can just copy-paste instead of replacing the `cost` variable with Blocks-specific `model.get_cost()` calls.

The reason I would like to avoid a `Model` abstraction anyway is because you're making the assumption that e.g. a model has "a cost". A model could easily have multiple costs, which are optimized in different ways by one algorithm. If you now want to make all models play nicely with all algorithms, we end up with a complicated interface that needs to be strung together by the main loop, which is what we would like to avoid (for example, what if two different algorithms need the same set of costs but in different order?). The logic of the main loop is currently effectively limited to `for batch in epoch: algorithm.process_batch(batch)`, which is nice and clean.

**Comment by rizar** [comment]
Just for the protocol: whether or not we need `Model` in Blocks is a subject of active discussion, see #347. But complete isolation of `blocks/algorithm` is something that we have already decided quite firmly. This part of the library works at the lower level possible to make it super-easy to add new algorithm and reuse available ones outside of Blocks. As a result it is already the most feature-full, because I would say it is the easiest to contribute to.

**Comment by adbrebs** [comment]
Ok, thank you for your answers.
