### ISSUE TITLE
Document pull request workflow

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#490]
Via comment on #489. Basically my feeling is it should go something like this, just need to write some textual explanation:

Do once:
```
git remote add upstream git@github.com:bartvm/blocks.git
```

Verify that `git remote -v |grep origin` points at your own fork.

When beginning a new pull request:
```
git fetch upstream
git checkout -b [ticket_branch_name] upstream/master
git push -u origin ticket_branch_name:ticket_branch_name
```

`git add -p` and `git commit` until satisfied.

```
git push origin ticket_branch_name
```

Send pull request from web interface. **Put 'Fixes #NNN' in the description field.**

----

Also document how to do a rebase.

**Comment by bartvm** [comment]
There are a lot of good Git tutorials out there, so I think we shouldn't re-invent the wheel more than we have to, but I guess it's useful to have a few very common workflows and issues documented.

The basic commands seem to be all in there, but I would tell people to update their local master as well so that they have something to rebase against. (Or can you rebase against `upstream/master`? Never tried.) So then it'd be `git fetch upstream`, `git checkout master`, `git merge upstream/master` followed by `git checkout -b [ticket_branch_name]`.

Oh, and doesn't `git push -u origin ticket_branch_name` work? One word less.

**Comment by dwf** [comment]
My goal isn't to write a full-fledged git tutorial (although some links are a good idea), but to provide a "quick reference"/"cheat sheet" that people can follow until it all sinks in and becomes second nature.

**Comment by dwf** [comment]
Yes, you can rebase against `upstream/master`. :)

**Comment by bartvm** [comment]
Learned something new then :)
