### ISSUE TITLE
Pull request docs have vanished off of ReadTheDocs

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#521]
All that goodness from #505 has vanished. It was there after merge.

**Comment by bartvm** [comment]
Ah, Read the Docs is very strange sometimes. Basically, when a build fails, it doesn't necessarily revert to the last successful build, but sometimes reverts to a random old version. The reason the build fails is very annoying: Since e.g. `picklable-itertools` isn't versioned (yet), there is no version listed in `requirements.txt`. This means that Read the Docs doesn't update the package when setting up the build environment, but all file imports then crash because e.g. `equizip` could not be imported. I tried wiping the cached build environment, but it only seems to respond to the wipe request one out of 10 times. In this case I actually think it succeeded with one build, installing the new `picklable-itertools`, but then failed again on a next one...

Anyway, normally these things are solved by sending 10 wipe requests and forcing it to rebuild a few times. I'll do that.

**Comment by bartvm** [comment]
Fixed!
