### ISSUE TITLE
Docstring inheritance

### ISSUE THREAD

**Issue by fvisin** [bartvm/blocks#544]
As we already discussed, it would be nice to inherit the docstring(s) from the superclass(es) to avoid:
* copy-pasted docstrings, as they quickly become outdated
* traversing the inheritance tree to know which attributes to set and how

I think that this Sphinx module could be of help, specifically the `:inherited-members:` flag
http://sphinx-doc.org/ext/autodoc.html

Also, for reference, a similar issue has been opened in pylearn2 a while ago: https://github.com/lisa-lab/pylearn2/issues/1410

**Comment by bartvm** [comment]
I'll voice the reservations I have with this again for the record as well: Inheriting NumPy docstrings is a bit of a nightmare, because the sections need to be in the right order, you need to get the whitespacing right, etc. This would also break al lot of the docstring checker we have (it would complain there is no summary line, because it'd be inherited from somewhere, etc.).  An entire docstring parsing framework that intelligently recombines multiple docstrings shouldn't go into blocks, but if someone wants to do that as a separate project, we could consider using it of course :) Also, keep in mind that people read docstrings in the code as much as they do in the rendered version, so I think there is something to say for having the docstring where it is needed (instead of having to open other files just to read the introduction).

**Comment by fvisin** [comment]
I agree but I thought it was worth mentioning and discussing nonetheless. I agree that addressing the documentation problem, should it be possible at all, would solve half of the problem only. But that would still be something! :) 

I strongly believe that copy-pasted documentation is evil and leads to poor documentation. I would enforce forcing the user traverse the inheritance tree rather than making the documentation unreliable.

In light of this, I would argue that having an "inherited documentation" section at the end of the docstring would still be better than not having it at all. This wouldn't break the docstring checker I guess (does it parse the sources or the sphinx output?).

I can't find an example of `:inherited-members:` applied to Numpy strings. Are you sure it doesn't behave correctly grouping together the elements belonging to the same docstring section?

**Comment by bartvm** [comment]
Docstring checker parses the source code directly.

Sphinx doesn't do any sort of docstring combination as far as I know. My understanding of `:inherited-members:` is something quite different; it decides whether inherited members should be documented.
```python
class Foo(object):
   def foo(self):
      pass

class Bar(Foo):
    def bar(self):
        pass
```
If I use `.. autoclass:: Bar` to document `Bar`, it won't show `Bar.foo` by default. With `:inherited-members:` turned on, it will render `Bar.foo` in the documentation. But if you do
```python
class Bar(Foo):
    def foo(self):
        pass

    def bar(self):
        pass
```
it won't make any attempt to intelligently combine the docstrings from `Bar.foo` and `Foo.foo`. It will simply take the one from `Bar.foo`.

In my mind, a lot of the problems you highlight are solved by using the `See Also` section judiciously. There's no need to copy paste then, just add a `See Also` section at the end with a link to the parents. In Sphinx these should be rendered as links, so it'll be easy to follow them.

**Comment by fvisin** [comment]
Ok, that's a pity. Thanks for the insight.
I thought it was good to open an issue about it so that we don't forget it, but I agree it's not a number one priority now, as you said when we spoke in person, so I am closing it for the moment.
