### ISSUE TITLE
Are auxilliary variables only "for" certain purposes?

### ISSUE THREAD

**Issue by dwf** [bartvm/blocks#547]
I'm trying to generically implement REINFORCE. The way that it works is essentially that the gradient of everything upstream of a stochastic decision is determined by a fake gradient for dC/d log p(action).

I think it makes most sense for stochastic hard-decision bricks to have the content of that decision as their apply output, and I can use `known_grads` to feed in the fake gradient for dC/d log p(action), but that implies having the expression for log p(action) in the graph somewhere.

My question is essentially, is this a valid use for an auxiliary variable? (I think the appropriate place for it is as an annotation on the decision variable, but my question is whether I should use the "auxiliary variable" machinery or not or just `add_annotation()`).

**Comment by EderSantana** [comment]
I think that problem may be similar to what we have trying to train GANs with Blocks...

First, can't you write the functional approximator of the hard decision function as a Theano graph and simply remove its parameters from the list of adaptive parameters? In that case the hard-decision brick should essentially be a cost brick that is `Initializable` with the expression for log p(action), right? I've done that once with Pylearn2...

... I just went to the docs and they say: 
> Auxiliary variables are Theano variables that are __not__ part of a brick’s output, but can be useful nonetheless e.g. as a regularizer or to monitor during training progress.

So I think we may either extend the definition of `auxiliary_variables` or add extra annotation like `FIXED` or non-adaptive. But since auxiliary are not listed in `ComputationalGraph.parameters` using them in that case should not cause any errors. 

What do you think?

**Comment by dwf** [comment]
Actually after an offline conversation with @bartvm I think this is exactly what I wanted. I can attach an auxiliary variable for the log probability of the action taken to the application call, and 

The issue isn't removing parameters, exactly. The reward you get is a function of the hard decision taken, and that hard decision has parameters, and they need to be trained somehow. REINFORCE essentially says to train those parameters by taking the gradient of the log probability of taking the action you took (assuming your policy gives you a distribution over which action is "the right one"), and multiplying it by `(r - b)`, where `r` is the reward and `b` is a baseline, essentially the reward you thought you would have gotten, estimated in some unspecified manner. One can short-circuit the gradient computation process by subbing in `r - b` as the gradient of the cost/negative reward with respect to the log probability of the action using `known_grads`, and then Theano should do the rest automatically.
