### ISSUE TITLE
Concurrent cost functions and params

### ISSUE THREAD

**Issue by EderSantana** [bartvm/blocks#551]
If we want to train a Generative Adversarial Network or a Reinforcement Learning model (as @dwf mentioned in #547 ), we face the problem of optimizing 2 cost functions (or more) in the same time. Also, some parameters that are adapted to optimize `cost 1` are considered fixed for `cost 2`. Thus, we cannot simply solve that summing both costs. In other words, we take turns in which parameters sets are we optimizing and which cost function are we considering.

We can handle that manually using `main_loop.algorithm.add_updates`. But wouldn't it be a better interface for the user to support that in the definition of `MainLoop`? If the user sets the cost to a `Tensor` he means the regular main loop (that get a `params` list), but if he uses a `dict` he means the adaptation of two concurrent graphs (he will have to pass a dict to `params` too).

What do you guys think? I may start working on that soon. Please, let me know if you have a better solutions for that (something like a hidden Theano feature that I don't know about for annotating the graph of `cost 1` and `cost 2` and allowing us to go back to simple cost function summation).

Thanks!

**Comment by dwf** [comment]
AFAICT this actually isn't relevant to the REINFORCE setup I was talking about. Also, rather than mucking with `add_updates`, you can derive the gradients you want manually using `tensor.grad` with `consider_constant`, and pass them in as the gradients argument of `GradientDescent`. I think this is a much more natural path and makes sure your `StepRule` gets applied correctly (of course, you can also apply different `StepRule`s to different parameters using `Restrict`).

**Comment by EderSantana** [comment]
I see, the RL that you are doing doesn't involve an adaptive smooth approximation of the cost function...
Also, your suggestions were pretty helpful!!! Thanks!!!

**Comment by rizar** [comment]
Is the question still open?

**Comment by dwf** [comment]
I don't know. I think there is probably room for a discussion of how to do things like GANs more naturally, where not all variables are differentiable with respect to all terms of the cost. But I think that the thing I suggested is probably the best we can do right now.
